### ISSUE TITLE
Add HTML Header Titles

### ISSUE THREAD

**Issue by aero31aero** [sakshamsharma/acehack#1]
Currently, your blog doesn't have dynamically generated titles, which might look good, or at least make it more user friendly. Instead of just "AceHack", something like "AceHack - Mini Gentoo Installation Log" might be useful.

Usecase: I currently have 5 of your blog posts open but I have no way of quickly figuring out which post is which just from the titles of different tabs.

**Comment by sakshamsharma** [comment]
Thanks a lot! I've fixed it now.
